// VIEWS
// WEEKLY MENU
export const VIEW_WEEKLY_MENU_CREATE = 'VIEW_WEEKLY_MENU_CREATE';
export const VIEW_WEEKLY_MENU_EDIT = 'VIEW_WEEKLY_MENU_EDIT';
export const VIEW_WEEKLY_MENU_LIST = 'VIEW_WEEKLY_MENU_LIST';
export const VIEW_WEEKLY_MENU_DETAIL = 'VIEW_WEEKLY_MENU_DETAIL';
export const VIEW_CURRENT_WEEKLY_MENU = 'VIEW_CURRENT_WEEKLY_MENU';


// COMMON STATES
export const LOADED = 'LOADED';
export const LOADING = 'LOADING';
export const ERROR = 'ERROR';


// LANG
export const CZECH_LANG = 'CZECH_LANG';
export const ENGLISH_LANG = 'ENGLISH_LANG';


// ROLES
export const AUTHORIZED = 'AUTHORIZED';
export const UNAUTHORIZED = 'UNAUTHORIZED';


// ENTITY STATES
// WEEKLY MENU
export const WEEKLY_MENU_DRAFT = 'WEEKLY_MENU_DRAFT';
export const WEEKLY_MENU_READY = 'WEEKLY_MENU_READY';
export const WEEKLY_MENU_PUBLISHED = 'WEEKLY_MENU_PUBLISHED';
export const WEEKLY_MENU_ARCHIVED = 'WEEKLY_MENU_ARCHIVED';