// WEEKLY MENU
// ACTIONS
export const ACTION_WEEKLY_MENU_CREATE = 'ACTION_WEEKLY_MENU_CREATE';
export const ACTION_WEEKLY_MENU_EDIT = 'ACTION_WEEKLY_MENU_EDIT';
export const ACTION_WEEKLY_MENU_LIST = 'ACTION_WEEKLY_MENU_LIST';
export const ACTION_WEEKLY_MENU_DETAIL = 'ACTION_WEEKLY_MENU_DETAIL';
export const ACTION_CURRENT_WEEKLY_MENU = 'ACTION_CURRENT_WEEKLY_MENU';

export const ACTION_MAKE_WEEKLY_MENU_CREATE = 'ACTION_MAKE_WEEKLY_MENU_CREATE';
export const ACTION_MAKE_WEEKLY_MENU_EDIT = 'ACTION_MAKE_WEEKLY_MENU_EDIT';
export const ACTION_MAKE_WEEKLY_MENU_DELETE = 'ACTION_MAKE_WEEKLY_MENU_DELETE';


// COMMON STATES
export const LOADED = 'LOADED';
export const LOADING = 'LOADING';
export const ERROR = 'ERROR';


// LANG
export const LANG_CZECH = 'cs';
export const LANG_ENGLISH = 'en';


// ROLES
export const AUTHORIZED = 'AUTHORIZED';
export const UNAUTHORIZED = 'UNAUTHORIZED';


// ENTITY STATES
// WEEKLY MENU
export const WEEKLY_MENU_DRAFT = 'WEEKLY_MENU_DRAFT';
export const WEEKLY_MENU_READY = 'WEEKLY_MENU_READY';
export const WEEKLY_MENU_PUBLISHED = 'WEEKLY_MENU_PUBLISHED';
export const WEEKLY_MENU_ARCHIVED = 'WEEKLY_MENU_ARCHIVED';